// <auto-generated />
using CSharpIntermediate.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSharpIntermediate.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220728181547_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CSharpIntermediate.Models.Manufacturer", b =>
                {
                    b.Property<int>("ManufacturerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("name")
                        .UseCollation("utf8mb4_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Name"), "utf8mb4");

                    b.HasKey("ManufacturerID");

                    b.ToTable("manufacturer");

                    b.HasData(
                        new
                        {
                            ManufacturerID = 1,
                            Name = "Chevrolet"
                        });
                });

            modelBuilder.Entity("CSharpIntermediate.Models.Model", b =>
                {
                    b.Property<int>("ModelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10)")
                        .HasColumnName("id");

                    b.Property<int>("ManufacturerID")
                        .HasColumnType("int(10)")
                        .HasColumnName("manufacturer_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("name")
                        .UseCollation("utf8mb4_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Name"), "utf8mb4");

                    b.HasKey("ModelID");

                    b.HasIndex("ManufacturerID")
                        .HasDatabaseName("FK_Model_Manufacturer");

                    b.ToTable("model");

                    b.HasData(
                        new
                        {
                            ModelID = 1,
                            ManufacturerID = 1,
                            Name = "Aveo"
                        },
                        new
                        {
                            ModelID = 2,
                            ManufacturerID = 1,
                            Name = "Corvette"
                        });
                });

            modelBuilder.Entity("CSharpIntermediate.Models.Model", b =>
                {
                    b.HasOne("CSharpIntermediate.Models.Manufacturer", "Manufacturer")
                        .WithMany("Models")
                        .HasForeignKey("ManufacturerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Model_Manufacturer");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("CSharpIntermediate.Models.Manufacturer", b =>
                {
                    b.Navigation("Models");
                });
#pragma warning restore 612, 618
        }
    }
}
